std_msgs/Header       header
bool                  recognition_finished_flag
bool                  recognition_success_flag
bool                  num_potential_target_valid_flag
bool                  potential_target_cluster_pose_valid_flag
int32                 num_potential_target
int32                 potential_target_source_file_index
geometry_msgs/Pose    potential_target_cluster_pose_in_arm_base_frame
